export const GUIDELINE_HUBS = [
  { label: 'AAP Clinical Practice Guidelines', url: 'https://www.aap.org/en/quality-improvement/clinical-practice-guidelines/' },
  { label: 'IAP Standard Treatment Guidelines', url: 'https://iapindia.org/standard-treatment-guidelines/' },
  { label: 'NEPAS Nepal Paediatric Society', url: 'https://nepas.org.np/' },
  { label: 'NICE Guidance', url: 'https://www.nice.org.uk/guidance' },
];

export const DISEASE_LIBRARY = [
  { id: 'asthma', title: 'Bronchial asthma exacerbation', category: 'Respiratory', summary: 'Severity assessment, bronchodilator/steroid pathway, response reassessment, and escalation prompts.', sources: [{ label: 'NICE NG80', url: 'https://www.nice.org.uk/guidance/ng80' }] },
  { id: 'seizure', title: 'Neonatal and pediatric seizure', category: 'Neurology', summary: 'Time-based seizure response, medication lookup, airway support, glucose/electrolyte checks, and escalation prompts.', sources: [{ label: 'AHA PALS', url: 'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/pediatric-advanced-life-support' }] },
  { id: 'refractory-seizure', title: 'Refractory status epilepticus', category: 'Neurology', summary: 'Structured refractory-seizure checklist for specialist escalation and continuous monitoring.', sources: [{ label: 'AHA PALS', url: 'https://cpr.heart.org/en/resuscitation-science/cpr-and-ecc-guidelines/pediatric-advanced-life-support' }] },
  { id: 'ards', title: 'Pediatric ARDS', category: 'Respiratory', summary: 'Severity documentation, respiratory support, monitoring, and escalation checklist for local protocol adaptation.', sources: [{ label: 'PALICC-2 overview', url: 'https://pubmed.ncbi.nlm.nih.gov/35088921/' }] },
  { id: 'septic-shock', title: 'Pediatric septic shock', category: 'Critical care', summary: 'Perfusion assessment, cultures/antimicrobials, fluid strategy, vasoactive support, and reassessment.', sources: [{ label: 'Surviving Sepsis Campaign', url: 'https://www.sccm.org/clinical-resources/surviving-sepsis-campaign-guidelines-2020' }, { label: 'NEPAS Nepal Paediatric Society', url: 'https://nepas.org.np/' }] },
  { id: 'shock', title: 'Pediatric shock pathways', category: 'Critical care', summary: 'Hypovolemic, distributive, cardiogenic, obstructive, and mixed shock assessment prompts.', sources: [{ label: 'Surviving Sepsis Campaign', url: 'https://www.sccm.org/clinical-resources/surviving-sepsis-campaign-guidelines-2020' }] },
  { id: 'pneumonia', title: 'Community-acquired pneumonia', category: 'Infectious disease', summary: 'Severity, oxygenation, hydration, antimicrobial selection prompts, and review criteria.', sources: [{ label: 'WHO pneumonia guidance', url: 'https://www.who.int/news-room/fact-sheets/detail/pneumonia' }, { label: 'AAP guideline hub', url: 'https://www.aap.org/en/quality-improvement/clinical-practice-guidelines/' }] },
  { id: 'diarrhea', title: 'Acute diarrhea and dehydration', category: 'Gastroenterology', summary: 'Hydration severity, oral/IV rehydration prompts, electrolyte safety, and monitoring.', sources: [{ label: 'WHO diarrhea guidance', url: 'https://www.who.int/news-room/fact-sheets/detail/diarrhoeal-disease' }] },
  { id: 'dka', title: 'Diabetic ketoacidosis', category: 'Endocrinology', summary: 'Recognition, fluid/electrolyte monitoring, insulin safety checks, and cerebral injury warning prompts.', sources: [{ label: 'ISPAD resources', url: 'https://www.ispad.org/page/ISPADGuidelines2022' }] },
  { id: 'anaphylaxis', title: 'Anaphylaxis', category: 'Emergency', summary: 'Immediate recognition, intramuscular adrenaline workflow, airway observation, and biphasic reaction monitoring.', sources: [{ label: 'Resuscitation Council UK', url: 'https://www.resus.org.uk/library/additional-guidance/guidance-anaphylaxis' }] },
  { id: 'bronchiolitis', title: 'Bronchiolitis', category: 'Respiratory', summary: 'Supportive care, feeding/hydration assessment, oxygen thresholds, and escalation prompts.', sources: [{ label: 'NICE NG9', url: 'https://www.nice.org.uk/guidance/ng9' }, { label: 'IAP guideline hub', url: 'https://iapindia.org/standard-treatment-guidelines/' }] },
  { id: 'meningitis', title: 'Suspected meningitis', category: 'Infectious disease', summary: 'Time-critical recognition, stabilization, antimicrobial escalation, and isolation prompts.', sources: [{ label: 'WHO meningitis guidance', url: 'https://www.who.int/news-room/fact-sheets/detail/meningitis' }] },
];
